# Generated by Django 5.1.7 on 2025-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_add_default_academic_years_semesters"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="academicyear",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="semester",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="name",
            field=models.CharField(
                choices=[
                    ("1", "First Year"),
                    ("2", "Second Year"),
                    ("3", "Third Year"),
                    ("4", "Fourth Year"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                choices=[("1", "Semester 1"), ("2", "Semester 2")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
