# Generated by Django 5.2 on 2025-04-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "resources",
            "0003_alter_academicyear_options_alter_semester_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="youtube_embed_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="youtube_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="resources/"),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF Document"),
                    ("WORD", "Word Document"),
                    ("VIDEO", "Video File"),
                    ("YOUTUBE", "YouTube Video"),
                    ("IMAGE", "Image"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
